=== KrishnaSuravarapu/OpenLipi/docs/schema/layout.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OpenLipi Layout",
  "type": "object",
  "required": ["layout_name", "mappings"],
  "properties": {
    "layout_name": { "type": "string" },
    "mappings": {
      "type": "object",
      "additionalProperties": { "type": "string" }
    },
    "special_rules": {
      "type": "object",
      "additionalProperties": { "type": "string" }
    },
    "consonants": {
      "type": "array",
      "items": { "type": "string" }
    },
    "matra_map": {
      "type": "object",
      "additionalProperties": { "type": "string" }
    }
  },
  "additionalProperties": false
}

=== KrishnaSuravarapu/OpenLipi/layouts/telugu/apple.json
{
  "layout_name": "Apple Telugu",
  "consonants": [
    "క", "ఖ", "గ", "ఘ", "ఙ", "చ", "ఛ", "జ", "ఝ", "ఞ", 
    "ట", "ఠ", "డ", "ఢ", "ణ", "త", "థ", "ద", "ధ", "న", 
    "ప", "ఫ", "బ", "భ", "మ", "య", "ర", "ల", "వ", "శ", 
    "ష", "స", "హ", "ళ", "క్ష", "ఱ"
  ],
  "matra_map": {
    "అ": "ా", "ఆ": "ా", "ఇ": "ి", "ఈ": "ీ", "ఉ": "ు", 
    "ఊ": "ూ", "ఋ": "ృ", "ఎ": "ె", "ఏ": "ే", "ఐ": "ై", 
    "ఒ": "ొ", "ఓ": "ో", "ఔ": "ౌ"
  },
  "mappings": {
    "q": "అ", "Q": "క్ష్మి",
    "w": "ఈ", "W": "ఋ",
    "e": "ఆ", "E": "ఋూ",
    "r": "ఇ", "R": "జ",
    "t": "ఒ", "T": "ఞ",
    "y": "ఓ", "Y": "క్ష",
    "u": "ఎ", "U": "శ్రీ",
    "i": "ఉ", "I": "/",
    "o": "ఏ", "O": "స్త్ర",
    "p": "ఊ", "P": "ష్ట్ర",
    "[": "ఐ", "{": "క్ష్మ",
    "]": "ఔ", "}": "!",
    
    "a": "ల", "A": "ళ",
    "s": "త", "S": "థ",
    "d": "ద", "D": "ధ",
    "f": "వ", "F": "శ",
    "g": "ం", "G": "ః",
    "h": "్", "H": "్",
    "j": "క", "J": "ఖ",
    "k": "ర", "K": "ఱ",
    "l": "న", "L": "ణ",
    ";": "ప", ":": "ఫ",
    "'": "స", "\"": "ష",
    
    "z": "ట", "Z": "ఠ",
    "x": "గ", "X": "ఘ",
    "c": "డ", "C": "ఢ",
    "v": "బ", "V": "భ",
    "b": "మ", "B": "హ",
    "$": "₹",
    "n": "య", "N": "క్ష్మీ",
    "m": "చ", "M": "ఛ"
  },
  "special_rules": {
    "h": "్",
    "g": "ం"
  }
}
